refactor: Refactorizacion de accion deploy

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -26,27 +26,15 @@ jobs:
         run: |
           ssh-keyscan -H 107.178.98.246 >> ~/.ssh/known_hosts
 
-      - name: Install sshpass
-        run: |
-          sudo apt-get update
-          sudo apt-get install -y sshpass
-
       - name: Deploy to Windows
-        env:
-          SSH_PASSWORD: ${{ secrets.SSH_PWD_USER }} # Carga la contraseña desde los secretos
         run: |
-          sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no -o PreferredAuthentications=keyboard-interactive,password -p 22 administrator@107.178.98.246 << 'EOF'
+          ssh -vvv -o StrictHostKeyChecking=no -o PreferredAuthentications=keyboard-interactive,password -p 22 administrator@107.178.98.246 << 'EOF'
             # Cambiar directorio de la aplicación
             cd /c/Cistem/dev/task-app || { echo "Error al cambiar de directorio"; exit 1; }
 
-            # Verificar si Git está en el PATH
-            if ! git --version > /dev/null 2>&1; then
-              echo "Git no está en el PATH, añadiendo temporalmente"
-              export PATH=$PATH:"/c/Program Files/Git/bin"
-            fi
-
-            # Verificar si Git está instalado
-            git --version || { echo "Git no está instalado"; exit 1; }
+            # Verificar el estado de Git
+            git status || { echo "Error al verificar el estado de Git"; exit 1; }
+            git branch -vv || { echo "Error al verificar ramas"; exit 1; }
 
             # Actualizar la aplicación
             git pull origin staging || { echo "Error al hacer git pull"; exit 1; }
