refactor: Refactorizacion en Accion deploy

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -26,18 +26,27 @@ jobs:
         run: |
           ssh-keyscan -H 107.178.98.246 >> ~/.ssh/known_hosts
 
-      - name: Deploy to Windows
+      - name: Install sshpass
         run: |
-          ssh -vvv -o StrictHostKeyChecking=no -o PreferredAuthentications=keyboard-interactive,password -p 22 administrator@107.178.98.246 << 'EOF'
+          sudo apt-get update
+          sudo apt-get install -y sshpass
+
+      - name: Deploy to Windows
+        env:
+          SSH_PASSWORD: ${{ secrets.SSH_PWD_USER }} # Carga la contraseña desde los secretos
+        run: |
+          sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no -o PreferredAuthentications=keyboard-interactive,password -p 22 administrator@107.178.98.246 << 'EOF'
             # Cambiar directorio de la aplicación
             cd /c/Cistem/dev/task-app || { echo "Error al cambiar de directorio"; exit 1; }
 
-            # Verificar el estado de Git
-            git status || { echo "Error al verificar el estado de Git"; exit 1; }
-            git branch -vv || { echo "Error al verificar ramas"; exit 1; }
+            # Verificar el estado del repositorio
+            git status || { echo "Error: el repositorio tiene cambios sin confirmar"; exit 1; }
+
+            # Asegurarse de estar en la rama correcta
+            git checkout staging || { echo "Error al cambiar a la rama staging"; exit 1; }
 
             # Actualizar la aplicación
-            git pull origin staging || { echo "Error al hacer git pull"; exit 1; }
+            git pull origin staging || { echo "Error al hacer git pull: $?" ; exit 1; }
 
             # Verificar si npm está disponible
             npm --version || { echo "npm no está instalado"; exit 1; }
